import csv
from functools import cached_property
from pathlib import Path
from urllib.parse import urljoin

import bs4
import requests

from lego_manual_downloader.config import BricksetConfig, Config
from lego_manual_downloader.files import atomic_write
from lego_manual_downloader.http import new_session
from lego_manual_downloader.lego import LegoSet
from lego_manual_downloader.providers import (
    AuthenticatedProvider,
    ManualProvider,
    OwnedSetsProvider,
)

_LOGIN_URL = "/login"
_LOGIN_FORM_ID = "aspnetForm"
_AUTH_COOKIE = ".ASPXAUTH"


class BricksetLoginError(Exception):
    pass


def _build_login_payload(form: bs4.Tag, username: str, password: str) -> dict[str, str]:
    """Fill in the ASP.NET WebForms login form, preserving its hidden state fields.

    Control names (ctl00$mainContent$ctl11 and friends) are generated by ASP.NET and
    change between renders, so every field is read off the form rather than hardcoded.
    """
    payload: dict[str, str] = {}
    filled: set[str] = set()
    for field in form.find_all("input"):
        name = field.get("name")
        if not name:
            continue
        field_type = field.get("type", "text").lower()
        if field_type == "password":
            payload[name] = password
            filled.add("password")
        elif field_type == "text":
            payload[name] = username
            filled.add("username")
        elif field_type == "checkbox":
            payload[name] = "on"  # "Remember Me" checkbox
        else:
            payload[name] = field.get("value", "")

    missing = {"username", "password"} - filled
    if missing:
        raise BricksetLoginError(f"Brickset login form has no {' or '.join(sorted(missing))} field")
    return payload


def _find_error_message(html: str) -> str:
    soup = bs4.BeautifulSoup(html, "html5lib")
    for element in soup.select(".error, .errorMessage, .validationSummary"):
        message = element.get_text(strip=True)
        if message:
            return message
    return "Brickset rejected the credentials"


class Brickset(AuthenticatedProvider, OwnedSetsProvider, ManualProvider):
    label = "brickset"

    def __init__(self, config: Config) -> None:
        if config.brickset is None:
            raise ValueError("Brickset provider requires 'brickset' section in config")
        if not config.brickset.username or not config.brickset.password:
            raise ValueError("Brickset provider requires 'username' and 'password' in config")
        self.config: BricksetConfig = config.brickset
        self.owned_sets_url = urljoin(self.config.base_url, self.config.owned_sets_url)
        self.instructions_url = urljoin(self.config.base_url, self.config.instructions_url)

    def login(self) -> requests.Session:
        "Login to brickset.com and return a session with the auth cookie."
        session = new_session()

        login_url = urljoin(self.config.base_url, _LOGIN_URL)
        login_page = session.get(login_url)
        login_page.raise_for_status()

        form = bs4.BeautifulSoup(login_page.text, "html5lib").find("form", id=_LOGIN_FORM_ID)
        if not isinstance(form, bs4.Tag):
            raise BricksetLoginError(f"No form #{_LOGIN_FORM_ID} at {_LOGIN_URL}")

        payload = _build_login_payload(form, self.config.username, self.config.password)
        response = session.post(
            login_url,
            data=payload,
            headers={"Origin": self.config.base_url, "Referer": login_url},
        )
        response.raise_for_status()

        if _AUTH_COOKIE not in session.cookies:
            raise BricksetLoginError(_find_error_message(response.text))
        return session

    @cached_property
    def instructions(self) -> dict[str, str]:
        """Get a mapping of set numbers to lego.com instruction PDF URLs from
        the Brickset export CSV.
        """
        response = self.session.get(self.instructions_url)
        response.raise_for_status()
        return {
            line["SetNumber"]: line["URL"]
            for line in csv.DictReader(response.text.splitlines())
            if line["URL"]
        }

    def get_owned_sets(self) -> list[LegoSet]:
        """Get a list of owned sets from the Brickset export CSV."""
        response = self.session.get(self.owned_sets_url)
        response.raise_for_status()
        return [
            LegoSet(line["Number"], line["Set name"], line["Year"])
            for line in csv.DictReader(response.text.splitlines())
        ]

    def download_manual(self, lego_set: LegoSet, output_path: Path) -> bool:
        url = self.instructions.get(lego_set.number)
        if not url:
            return False
        with self.session.get(url, stream=True) as r:
            r.raise_for_status()
            with atomic_write(output_path) as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)
        return True
